version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_tesis
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - RUTA_MODELO=./modelos
    networks:
      - app-network
    volumes:
      - ./modelos:/app/modelos  # Monta la carpeta modelos local dentro del contenedor

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
